QEMU_CMD="qemu-system-loongarch64 -M virt -cpu la464"
QEMU_KCONFIG="
CONFIG_SERIAL_8250=y
CONFIG_SERIAL_8250_CONSOLE=y
# CONFIG_KEYBOARD_ATKBD is not set
# CONFIG_MOUSE_PS2 is not set
# CONFIG_SERIO_I8042 is not set
"
KERNEL_IMAGE="vmlinux.efi"
KERNEL_CMDLINE="console=ttyS0 earlycon"
