QEMU_EFI="${QEMU_EFI:-/usr/share/edk2/loongarch64/QEMU_EFI.fd}"
QEMU_CMD="qemu-system-loongarch64 -M virt -cpu la464 -bios $QEMU_EFI"
QEMU_KCONFIG="
CONFIG_ACPI_SPCR_TABLE=y
CONFIG_PCI_HOST_GENERIC=y
CONFIG_SERIAL_8250=y
CONFIG_SERIAL_8250_CONSOLE=y
CONFIG_SPARSEMEM_MANUAL=y
"
KERNEL_IMAGE="vmlinux.efi"
KERNEL_CMDLINE="console=ttyS0 earlycon"
