/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _ASM_X86_IBS_MPROF_H
#define _ASM_X86_IBS_MPROF_H

/*
 * All bits are documented here for clarity even if the current
 * driver doesn't use all of them.
 */

/* MSR_AMD64_IBS_MPROF_DATA2 bits */
#define IBS_MPROF_DATA2_DATASRC_MASK		0x7
#define IBS_MPROF_DATA2_DATASRC_MASK_HIGH	0xC0
#define IBS_MPROF_DATA2_DATASRC_MASK_HIGH_SHIFT	0x3
#define IBS_MPROF_DATA2_DATASRC_LCL_CCX		0x1
#define IBS_MPROF_DATA2_DATASRC_PEER_CCX_NEAR	0x2
#define IBS_MPROF_DATA2_DATASRC_DRAM		0x3
#define IBS_MPROF_DATA2_DATASRC_CCX_FAR		0x5
#define IBS_MPROF_DATA2_DATASRC_EXT_MEM		0x8
#define IBS_MPROF_DATA2_RMT_NODE		BIT_ULL(4)
#define IBS_MPROF_DATA2_RMT_SOCKET		BIT_ULL(9)

/* MSR_AMD64_IBS_MPROF_DATA3 bits */
#define IBS_MPROF_DATA3_LDOP		BIT_ULL(0)
#define IBS_MPROF_DATA3_STOP		BIT_ULL(1)
#define IBS_MPROF_DATA3_DCMISS		BIT_ULL(7)
#define IBS_MPROF_DATA3_LADDR_VALID	BIT_ULL(17)
#define IBS_MPROF_DATA3_PADDR_VALID	BIT_ULL(18)
#define IBS_MPROF_DATA3_L2MISS		BIT_ULL(20)
#define IBS_MPROF_DATA3_SW_PREFETCH	BIT_ULL(21)

/* MSR_AMD64_IBS_MPROF_CTL bits */
#define IBS_MPROF_CTL_CNT_CTL		BIT_ULL(19)
#define IBS_MPROF_CTL_VAL		BIT_ULL(18)
#define IBS_MPROF_CTL_ENABLE		BIT_ULL(17)
#define IBS_MPROF_CTL_L3MISSONLY	BIT_ULL(16)
#define IBS_MPROF_CTL_MAXCNT_MASK	0x0000FFFFULL
#define IBS_MPROF_CTL_MAXCNT_EXT_MASK	(0x7FULL << 20)	/* separate upper 7 bits */

/* MSR_AMD64_IBS_MPROF_CTL2 bits */
#define IBS_MPROF_CTL2_DISABLE		BIT_ULL(0)
#define IBS_MPROF_CTL2_EXCLUDE_USER	BIT_ULL(1)
#define IBS_MPROF_CTL2_EXCLUDE_KERNEL	BIT_ULL(2)

#define IBS_MPROF_SAMPLE_PERIOD	10000

#endif /* _ASM_X86_IBS_MPROF_H */
