name: MM Host Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:

  host-tests:
    name: Run MM host tests
    runs-on: self-hosted

    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: Run memblock tests
        run: bash -x .github/scripts/run-memblock-tests.sh

#      - name: Run radix-tree tests
#        run: bash .github/scripts/run-radix-tree-tests.sh

      - name: Run VMA tests
        run: bash .github/scripts/run-vma-tests.sh
