name: MM Tests Setup

on:
  workflow_call:  # Makes this workflow reusable

jobs:
  setup:
    name: Setup test environment
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        run: bash .github/scripts/checkout.sh

      - name: Install dependencies
        working-directory: linux
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y build-essential libasan6 liburcu-dev
